README.md
Sources/AIProxy/AIProxyDeviceCheck.swift
Sources/AIProxy/AIProxyError.swift
Sources/AIProxy/OpenAI/OpenAIChatCodables.swift
Sources/AIProxy/OpenAI/OpenAIService.swift
Tests/AIProxyTests/OpenAIServiceTests.swift

- OpenAI can return JSON messages as part of the chat completion response. See the `response_format` description [in the OpenAI Chat reference](https://platform.openai.com/docs/api-reference/chat/create) for details.
- This patch adds support for JSON messages, and updates the README to include a usage example

Add support for OpenAI's JSON message response

---

README.md
Sources/AIProxy/OpenAI/OpenAIService.swift

- The previous implementation sent the DeviceCheck bypass token from all devices, provided the token was available as an env variable. We only want to use the bypass token for simulator, where DeviceCheck is not available
- Added a FAQ to the README and included blurbs on the bypass token and the aiproxy partial key

Only send DeviceCheck bypass from simulator

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/OpenAI/OpenAIChatCodables.swift
Sources/AIProxy/OpenAI/OpenAIService.swift
Sources/AIProxy/OpenAI/OpenAIUtils.swift
Tests/AIProxyTests/OpenAIServiceTests.swift

- Added codable representations for OpenAI's streaming chat objects
- Added `AIProxy.openAIEncodedImage(image:)` helper function to encode a UIImage or NSImage into the format that OpenAI expects
- Added `OpenAIService#streamingChatCompletionRequest` as the entry point for kicking off streaming chats
- Made non-200 status codes available to the caller in the new streaming chat case. This is handy if you'd like to take special action on `429` (rate limited).
- Added streaming example and multi-modal example (sending an image and text in the request) to README.md

Add support for streaming chat completions from OpenAI

---

Package.swift

- Support developers using an older version of Xcode
- I tested this back to Xcode 15.0.1, and up to Xcode 16.0 beta 3
- This change addresses the following error:
```
Dependencies could not be resolved because 'aiproxyswift' contains incompatible tools version (5.10.0)
```

Drop minimum swift version to 5.9

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/OpenAI/OpenAIService.swift

- New customers are required to pass a `serviceURL` to the `AIProxy.openAIService` method:
- The service URL is displayed in the AIProxy dashboard when you submit your OpenAI key.
- This argument is required for keys that you submitted after July 22nd, 2024.
- If you are an existing customer that configured your AIProxy project before July 22nd, you may continue to leave this blank.
- This PR is in preparation for the v2 release of the backend
- Also added consistent 95 column breaks to the docstring

Add serviceURL to public parameters

---

README.md

Updated the readme with the modern way of calling the `openAIService` builder:
let openAIService = AIProxy.openAIService(
)
Customers that are on v1 services can safely omit the `serviceURL` argument.

Include serviceURL in initialization

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyUtils.swift
Sources/AIProxy/Anthropic/AnthropicMessageRequestBody.swift
Sources/AIProxy/Anthropic/AnthropicMessageResponseBody.swift
Sources/AIProxy/Anthropic/AnthropicService.swift
Tests/AIProxyTests/AnthropicMessageRequestTests.swift
Tests/AIProxyTests/AnthropicMessageResponseTests.swift

- Added support for proxying Anthropic API calls through AIProxy
- Added README examples for:
- Sending a text message to Claude
- Sending a multi-modal (text and image) message to Claude
- Sending a tool schema to Claude
The tool usage is interesting in that the request body accepts a `[String: Any]` schema to define the schema that Claude should adhere to. The special handling that juggles a mix of Encodable with JSONSerialization is related to this use case.

Add Anthropic support

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyHTTPVerb.swift
Sources/AIProxy/AIProxyURLRequest.swift
Sources/AIProxy/AIProxyURLSession.swift
Sources/AIProxy/Anthropic/AnthropicService.swift
Sources/AIProxy/DeepL/DeepLService.swift
Sources/AIProxy/OpenAI/OpenAIService.swift
Sources/AIProxy/StabilityAI/StabilityAIService.swift

- Added an example of fetching the weather with OpenMeteo through AIProxy
- Added new public methods for getting URLRequests and URLSessions that are configured for use with AIProxy
This patch provides public methods `AIProxy.request(...)` and `AIProxy.session()` that build their respective objects in a way that AIProxy expects. This makes it easier for developers that are writing their own clients, or that have an official client that they'd like to make work with AIProxy. For example, OpenMeteo already has an official lib. We don't want to recreate all of that lib in this package. Instead, we expose the parts of the core that are required to make the OpenMeteo lib communicate through our servers.
import AIProxy
import OpenMeteoSdk
do {
let request = try await AIProxy.request( …

Add OpenMeteo support

---

Sources/AIProxy/Replicate/ReplicateError.swift
Sources/AIProxy/Replicate/ReplicateService.swift

Previously, if a prediction failed on replicate we would continue polling a total of `pollAttempts` times. With this fix, the polling stops as soon as replicate returns a prediction status of `failed` or `canceled`

Bug fix: stop polling replicate on failed prediction

---

Package.swift

Hi! 
My app Meshing uses AIProxy and I want to use it in the visionOS project as well. I took a fork, and built AIProxySwift locally, and it works for Vision Pro with one line of change

Add visionOS support

---

Sources/AIProxy/Replicate/ReplicateFluxDevOutputSchema.swift
Sources/AIProxy/Replicate/ReplicateFluxProOutputSchema.swift
Sources/AIProxy/Replicate/ReplicateFluxSchnellOutputSchema.swift

Fix a regression in 0.16.0 which caused existing client code to throw compilation error:
```
Generic parameter 'U' could not be inferred
Cannot find type 'ReplicateFluxDevOutputSchemas' in scope
```

Make Flux replicate type aliases public

---

README.md
Sources/AIProxy/OpenAI/OpenAIChatCompletionRequestBody.swift

This change adds the `detail` parameter to chat completions, which has three options, low, high, or auto. 
This gives you control when using Vision (available for GPT-4o, GPT-4o mini, and GPT-4 Turbo) over how the model processes the image and generates its textual understanding. By default, the model will use the auto setting which will look at the image input size and decide if it should use the low or high setting.
`low` will enable the "low res" mode. The model will receive a low-res 512px x 512px version of the image, and represent the image with a budget of 85 tokens. This allows the API to return faster responses and consume fewer input tokens for use cases that do not require high detail.
`high` will enable "high res" mode, which first allows the model to first see the low res …

Add detail param to OpenAI chat completion

---

Sources/AIProxy/OpenAI/OpenAIService.swift

If a customer specifies that the whisper response format is text, then we don't want to json deserialize the http response body from OpenAI.
Before this change, a request format like the following would raise on the `let response = try` line:
```swift
let requestBody = OpenAICreateTranscriptionRequestBody(
file: try Data(contentsOf: url),
model: "whisper-1",
responseFormat: "text"
)
let response = try await openAIService.createTranscriptionRequest(body: requestBody)
```
This patch skips the use of Decodable and instead instantiates the `OpenAICreateTranscriptionResponseBody` directly using the http response body.
Thanks to Pierre for reporting!

Do not json deserialize whisper response for 'text' responseFormat

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/OpenAI/OpenAIRequestFormat.swift
Sources/AIProxy/OpenAI/OpenAIService.swift

You can use all of the OpenAI snippets in this project's README with one change. Initialize the OpenAI service with:
import AIProxy
let openAIService = AIProxy.openAIService(
serviceURL: "service-url-from-your-developer-dashboard",
requestFormat: .azureDeployment(apiVersion: "2024-06-01")
)

Add support for Azure deployments

---

Sources/AIProxy/OpenAI/OpenAIChatCompletionRequestBody.swift

Sample request:
```swift
let openAIService = AIProxy.openAIService(
)
do {
let response = try await openAIService.chatCompletionRequest(body: .init(
model: "gpt-4o-mini",
messages: [.assistant(content: .text("hello world"))]
))
print(response.choices.first?.message.content ?? "")
}  catch AIProxyError.unsuccessfulRequest(let statusCode, let responseBody) {
print("Received non-200 status code: \(statusCode) with response body: \(responseBody)")
} catch {
print(error.localizedDescription)
}
```

Add OpenAI assistant role to chat completions API

---

README.md
Sources/AIProxy/Fal/FalRunwalGen3AlphaInputSchema.swift
Sources/AIProxy/Fal/FalRunwayGen3AlphaOutputSchema.swift
Sources/AIProxy/Fal/FalService.swift

This PR adds Runway Gen3 Alpha (image to video) support on Fal. The request takes a prompt, image url, and optional duration.

Runway Gen3 Alpha Support for Fal

---

Sources/AIProxy/Fal/FalService.swift

Video generation takes longer than images (~ >30s) so the number of polling needed is higher. his bumps the attempts to 30 and the seconds between attempts to 2 seconds.

Increase polling attempts for image generation on Fal

---

README.md
Sources/AIProxy/Anthropic/AnthropicAsyncChunks.swift
Sources/AIProxy/Anthropic/AnthropicMessageStreamingChunk.swift
Sources/AIProxy/Anthropic/AnthropicMessageStreamingContentBlockStart.swift
Sources/AIProxy/Anthropic/AnthropicMessageStreamingDeltaBlock.swift
Sources/AIProxy/Anthropic/AnthropicService.swift
Tests/AIProxyTests/AnthropicMessageStreamingChunkTests.swift

import AIProxy
let anthropicService = AIProxy.anthropicService(
)
do {
let requestBody = AnthropicMessageRequestBody(
maxTokens: 1024,
messages: [
.init(
content: [.text("hello world")],
role: .user
)
],
model: "claude-3-5-sonnet-20240620"
)
let stream = try await anthropicService.streamingMessageRequest(body: requestBody)
for try await chunk in stream {
switch chunk {
case .text(let text):
print(text)
case .toolUse(name: let toolName, input: let toolInput):
print("Claude wants to call tool \(toolName) with input \(toolInput)")
}
}
}  catch AIProxyError.unsuccessfulRequest(let statusCode, let responseBody) {
print("Received non-200 status code: \(statusCode) with response body: …

Add support for Anthropic streaming messages and tool calls

---

README.md
Sources/AIProxy/OpenAI/OpenAIService.swift
Sources/AIProxy/OpenAI/OpenAITextToSpeechCodables.swift
Sources/AIProxy/OpenAI/OpenAITextToSpeechRequestBody.swift

How to use OpenAI's text to speech API
```swift
import AIProxy
let openAIService = AIProxy.openAIService(
)
do {
let requestBody = OpenAITextToSpeechRequestBody(
input: "Hello world",
voice: .nova
)
let mpegData = try await openAIService.createTextToSpeechRequest(body: requestBody)
// Do not use a local `let` or `var` for AVAudioPlayer.
// You need the lifecycle of the player to live beyond the scope of this function.
// Instead, use file scope or set the player as a member of a reference type with long life.
// For example, at the top of this file you may define:
//
//   fileprivate var audioPlayer: AVAudioPlayer? = nil
//
// And then use the code below to play the TTS result: …
```

Add support for OpenAI's text to speech API

---

Sources/AIProxy/Fal/FalService.swift

This PR adds `uploadFile(data: Data, name: String, contentType:)` to `FalService` to upload any arbitrary file to Fal's short term storage. For example, a use case is uploading a reference image for Runway, Flux Dev, or ControlNet.

Add FileUpload for uploading non-zip files to Fal

---

Package.swift
Sources/AIProxy/Resources/PrivacyInfo.xcprivacy

Added privacy manifest, which is used to generate the privacy "nutrition label" of the package.
AIProxy does not use any collected data for tracking, nor do we sell any data. The pieces of data we collect (IP address and DeviceID) are used for applying request rate limits, and for display in the 'Request History' tab of the developer dashboard. Our nutrition label looks like this:
According to [Apple](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk):
> Starting November 12, 2024, apps that don’t include a required privacy manifest can’t be submitted for review in App Store Connect
Closes: https://github.com/lzell/AIProxySwift/issues/28

Add privacy manifest

---

README.md
Sources/AIProxy/Replicate/ReplicateService.swift
Sources/AIProxy/Replicate/ReplicateSynchronousAPIOutput.swift

- Added support for Replicate's synchronous API, [announced here](https://replicate.com/changelog/2024-10-09-synchronous-api)
- Added deprecation notices to existing Flux-Schnell, Flux-Dev, and Flux-Pro methods that use polling
- Created new methods that the deprecation notices point to. The new methods use http long polling, meaning connections remain open until the prediction result is available. This reduces the number of requests that are made to AIProxy. Results also arrive faster, as we don't have to worry about a coarse polling interval.

Adopt replicate synchronous API for Flux generations

---

Package.swift
Sources/AIProxy/AIProxyIdentifier.swift

This PR adds support for watchOS. Only a handful of changes were required:
- Using the correct device identifier
- Made sure the Package targets watchOS 9 or newer (required for `DCDevice` to work)

Added support for watchOS

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/EachAI/EachAIError.swift
Sources/AIProxy/EachAI/EachAIService.swift
Sources/AIProxy/EachAI/EachAITriggerWorkflowRequestBody.swift
Sources/AIProxy/EachAI/EachAITriggerWorkflowResponseBody.swift
Sources/AIProxy/EachAI/EachAIWorkflowExecutionResponseBody.swift
Tests/AIProxyTests/EachAIWorkflowTests.swift
Tests/AIProxyTests/OpenAIChatCompletionRequestTests.swift
Tests/AIProxyTests/PerplexityChatCompletionResponseBodyTests.swift

- Adds support for kicking off a workflow execution and polling for the result.
- The trigger request is documented here: https://docs.eachlabs.ai/api-reference/flows/trigger-ai-workflow
- The polling request is documented here: https://docs.eachlabs.ai/api-reference/execution/get-flow-execution
- Swift example for calling your own workflow:
```swift
import AIProxy
let eachAIService = AIProxy.eachAIService(
)
// Update the arguments here based on your eachlabs use case:
let workflowID = "your-workflow-id"
let requestBody = EachAITriggerWorkflowRequestBody(
parameters: [
"img": "https://storage.googleapis.com/magicpoint/models/women.png"
]
)
do {
let triggerResponse = try await …
```

Add EachAI support

---

README.md
Sources/AIProxy/Anthropic/AnthropicDirectService.swift
Sources/AIProxy/Anthropic/AnthropicMessageRequestBody.swift
Sources/AIProxy/Anthropic/AnthropicProxiedService.swift

- PDFs can be included in chat completion requests to Anthropic.
- The README includes two examples:
1. pdf summarization with a buffered response
2. pdf summarization with a streaming response

Add Anthropic pdf support

---

Sources/AIProxy/AIProxyCertificatePinning.swift
Sources/AIProxy/AIProxyURLSession.swift

This allows us to create a subclass of the session delegate, to override functions for tracking progress (whilst still maintaining certificate pinning) such as:
```swift
func urlSession(_ session: URLSession, task: URLSessionTask, didSendBodyData bytesSent: Int64, totalBytesSent: Int64, totalBytesExpectedToSend: Int64)
```
and
```swift
func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data)
```
We can use it by simply overriding the delegate:
```swift
final class ProgressMonitoringSessionDelegate: AIProxyCertificatePinningDelegate {
...
}
AIProxyURLSession.delegate = ProgressMonitoringSessionDelegate()
```

Allow subclassing of AIProxyCertificatePinningDelegate

---

README.md
Sources/AIProxy/Perplexity/PerplexityChatCompletionRequestBody.swift
Sources/AIProxy/Perplexity/PerplexityChatCompletionResponseBody.swift

- Added `citations` to the response body
- Updated README examples to print citations after the response

Add citations to perplexity examples

---

README.md
Sources/AIProxy/AIProxyJSONValue.swift
Sources/AIProxy/OpenAI/OpenAIChatCompletionRequestBody.swift
Sources/AIProxy/OpenAI/OpenAIChatCompletionResponseBody.swift
Sources/AIProxy/SingleOrPartsEncodable.swift
Tests/AIProxyTests/OpenAIChatCompletionRequestTests.swift

- Added codables for passing function call information back to OpenAI
- See the guide on using [OpenAI function calls in swift](https://www.aiproxy.com/update/2025/01/17/OpenAI-function-calls-in-swift.html)
- Closes issue: https://github.com/lzell/AIProxySwift/issues/87

Support passing function call results back to OpenAI

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyURLRequest.swift
Sources/AIProxy/ReceiptValidation/ReceiptValidationRequestBody.swift
Sources/AIProxy/ReceiptValidation/ReceiptValidationResponseBody.swift
Sources/AIProxy/ReceiptValidation/ReceiptValidationService.swift

- Sends the contents of AppTransaction up to AIProxy
- Note that this does not happen automatically! Customers opt-in to use this service
- Adds the bundle ID and library version to metadata that goes up with all AIProxy requests

Add a receipt validation service

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/FireworksAI/FireworksAIDirectService.swift
Sources/AIProxy/FireworksAI/FireworksAIProxiedService.swift
Sources/AIProxy/FireworksAI/FireworksAIService.swift

- AIProxySwift can be used to make requests directly to Fireworks AI or protected through our backend.
- Customers should configure their AIProxy service to use proxy domain `api.fireworks.ai`
- Added a readme example of streaming R1 use
- Added a readme example of buffered R1 use

Add Fireworks AI support for DeepSeek

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/Replicate/ReplicateError.swift
Sources/AIProxy/Replicate/ReplicateService+Convenience.swift
Sources/AIProxy/Replicate/ReplicateService.swift
Sources/AIProxy/Replicate/ReplicateSynchronousAPIOutput.swift
Tests/AIProxyTests/OpenAIChatCompletionRequestTests.swift
Tests/AIProxyTests/ReplicateSyncAPIResponseBodyTests.swift

- Enforce caller to supply the `secondsToWait` argument to communicate how the sync API works
- Rename `ReplicateSynchronousAPIOutput` to `ReplicateSynchronousResponseBody` (the old name will still compile)
- DRY the replicate convenience methods
- Expose `ReplicateService.synchronousResponseBodyToOutput`, which gets the inference result from the response body (or it transparently makes a subsequent request to Replicate if the inference result is not inline on the sync response body)

Touch up Replicate convenience helpers

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AnonymousAccount/AIProxyKeychain.swift
Sources/AIProxy/AnonymousAccount/AIProxyStorage.swift
Sources/AIProxy/AnonymousAccount/AnonymousAccount.swift
Sources/AIProxy/AnonymousAccount/AnonymousAccountStorage.swift

- Writes a local anonymous ID to keychain
- Attempts to sync a stable, anonymous ID across keychain backed by iCloud
- Attempts to sync a stable, anonymous ID across NSUbiquitousKeyValueStore
- Resolution logic picks the ID that was created earliest, and synchronizes the resolved identifier with the three sources
This gives us a best-effort anonymous ID that is stable across multiple devices of an iCloud account

Add support for anonymous accounts

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/OpenAI/OpenAIDirectService.swift
Sources/AIProxy/OpenAI/OpenAIProxiedService.swift
Sources/AIProxy/OpenAI/OpenAIService.swift

- Added a `secondsToWait` parameter that holds off on raising `URLError.timedOut` until `secondsToWait` elapses
- Default timeout remains at 60 seconds, but the caller can customize how long they are willing to wait for their application.
- Added a README example using o3-mini

Add extended timeout for OpenAI requests to o1 and o3-mini

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/Replicate/ReplicateDirectService.swift
Sources/AIProxy/Replicate/ReplicateError.swift
Sources/AIProxy/Replicate/ReplicateFileUploadRequestBody.swift
Sources/AIProxy/Replicate/ReplicatePredictionRequestBody.swift
Sources/AIProxy/Replicate/ReplicatePredictionResponseBody.swift
Sources/AIProxy/Replicate/ReplicateProxiedService.swift
Sources/AIProxy/Replicate/ReplicateService+Convenience.swift
Sources/AIProxy/Replicate/ReplicateService.swift
Sources/AIProxy/Replicate/ReplicateSynchronousAPIOutput.swift
Sources/AIProxy/Replicate/ReplicateTrainingResponseBody.swift
Tests/AIProxyTests/ReplicatePredictionResponseBodyTests.swift
Tests/AIProxyTests/ReplicateSyncAPIResponseBodyTests.swift

Replicate users of the lib no longer have to juggle many calls into the replicate service from their calling code. We provide high level calls `runCommunityModel` and `runOfficialModel` that use the synchronous API for the allotted time, and then automatically fall back to polling if that time is exceeded.
Further, I had previously abstracted away the prediction object. This was not great, there may be things that developers want to do in the case of failure (look at logs, look at metrics, show the error message) that are easier by exposing the prediction object to the caller. So now those objects are exposed.
You can make a prediction using either `replicateService.runCommunityModel` or `replicateService.runOfficialModel`, both of which return the prediction object in a terminal state …

Add automatic fallback to polling API for replicate requests

---

README.md

- Steps to create encodables / decodables for a service that we don't have built-in support for
- How to sniff the request/response bodies of official clients

Add instructions for proxying a custom service

---

Sources/AIProxy/Anthropic/AnthropicMessageRequestBody.swift
Sources/AIProxy/Anthropic/AnthropicMessageResponseBody.swift

Add the required changes to respond back to Anthropic with the tool use and tool response options. Example usage: 
```swift
for content in response.content {
switch content {
case .text(let message):
print("MESSAGE: \(message)")
messages.append(
.init(
content: [.text(message)],
role: .assistant
)
)
case .toolUse(id: let id, name: let toolName, input: let toolInput):
if toolName == "mytool" {
if case .string(let thought) = toolInput["myinput"]  {
print("TOOL: \(myinput)")
messages.append(
.init(
content: [.toolUse(id: id, name: toolName, input: toolInput)],
role: .assistant
)
)
messages.append(
.init(
content: [.toolResult(toolUseId: id, content: thought)], role: .user
)
)
try await callClaude()
} else {
print("Claude used the think tool with invalid input: \(toolInput)")
}
} else { …
```

improved tool use with anthropic

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyDeviceCheck.swift
Sources/AIProxy/AIProxyURLRequest.swift
Sources/AIProxy/BackgroundNetworker.swift
Sources/AIProxy/ClientLibErrorLogger.swift

- Logs additional information when the lib fails to get a DC token
- Motivation: I'm seeing sporadic requests that come in with a DeviceCheck header. The requests otherwise do not look fraudulent, so I think they are from failures in Apple's framework.

Add device check error logging

---

README.md

Love this repo! Cleaning up the README:
- Add proper Swift syntax highlighting markers to code examples
- Fix indentation and whitespace in code blocks
- Correct string formatting error in DeepSeek example

Fix code block formatting in README.md

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/OpenRouter/OpenRouterChatCompletionRequestBody.swift

The `includeReasoning` property is deprecated. OpenRouter prefers the following:
Do not include reasoning in the response:
```
reasoning: .init(exclude: true)
```
Include reasoning at different levels:
```
reasoning: .init(effort: .low)  // Or .medium, high
```

Add reasoning to OpenRouter chat completion

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/Gemini/GeminiDirectService.swift
Sources/AIProxy/Gemini/GeminiProxiedService.swift
Sources/AIProxy/Gemini/GeminiService.swift

Some image generations requests take longer than 60 seconds. I'm now enforcing that callers supply the timeout that makes sense for them. The docstring and README samples have a suggestion for folks that don't want to think about it.
I'm going to do this for more services and methods.
Relates to https://github.com/lzell/AIProxySwift/pull/121

Add seconds to wait param for gemini

---

Sources/AIProxy/OpenAI/OpenAITextToSpeechRequestBody.swift

Summary
This PR extends the TTS capabilities by introducing support for a new TTS model (gpt-4o-mini-tts) and several additional voices.
What’s Changed
- Added gpt-4o-mini-tts to the list of supported models in OpenAITextToSpeechRequestBody.Model.
- Added new voice options (ash, ballad, coral, sage) to the Voice enum.
Notes
- These changes are backward-compatible and extend current functionality.

Add support for new TTS model and additional voices

---

README.md
Sources/AIProxy/OpenAI/OpenAICreateResponseRequestBody.swift
Tests/AIProxyTests/OpenAICreateResponseRequestTests.swift

Allows the Chat Responses API to pass in a` previous_response_id`, allowing a user to pass in a single ID of a long conversation instead of manually passing in the entire chat history. This is the [recommended way to share entire chat](https://platform.openai.com/docs/guides/conversation-state#openai-apis-for-conversation-state) histories, but the parameter was missing in the request.
This PR adds the missing parameter, and a matching test case. It also updates the documentation to reflect this change.
Per the OpenAPI documentation:
Share context across generated responses with the previous_response_id parameter. This parameter lets you chain responses and create a threaded conversation.
https://platform.openai.com/docs/guides/conversation-state?api-mode=responses#openai-apis-for-conversat …

OpenAI Responses - Add PreviousResponseId to requests

---

Sources/AIProxy/OpenAI/OpenAICreateResponseRequestBody.swift
Sources/AIProxy/OpenAI/OpenAIResponse.swift

Added option to use the previous_response_id parameter in the responses API. Example: 
```swift
let additionRequestBody = OpenAICreateResponseRequestBody(
input: .text("what is 2 + 2?"),
model: "gpt-4o",
previousResponseId: nil
)
let additionResponse: OpenAIResponse = try await openAIService.createResponse(requestBody: additionRequestBody)
print(additionResponse.outputText) // "2 + 2 = 4"
let multiplicationRequestBody = OpenAICreateResponseRequestBody(
input: .text("now multiply that by 2"),
model: "gpt-4o",
previousResponseId: additionResponse.id // include reference to the previous messages
)
let multiplicationResponse: OpenAIResponse = try await openAIService.createResponse(requestBody: multiplicationRequestBody)
print(multiplicationResponse.outputText) // Multiplying 4 by 2 gives you …
```

added previous response id for OpenAI responses API

---

Sources/AIProxy/OpenAI/OpenAITextToSpeechRequestBody.swift

- OpenAI TTS API includes a new field called `instructions`  to prompt `gpt-4o-mini-tts`.

Add optional `instructions` field for openai new TTS model

---

Sources/AIProxy/Gemini/GeminiGenerateContentRequestBody.swift
Sources/AIProxy/Gemini/GeminiGenerateContentResponseBody.swift
Tests/AIProxyTests/GeminiGenerateContentRequestTests.swift

Since `Gemini-2.5 Flash` is a hybrid model, you can enable/disabe thinking by specifying a `thinkingBudget` inside this field. If `0` then thinking is disabled, if `> 0` thinking is enabled and max tokens is capped at that int.

Add optional `thinkingConfig` field for the new Gemini 2.5 flash model

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyIdentifier.swift
Sources/AIProxy/AIProxyURLRequest.swift
Sources/AIProxy/AnonymousAccount/AnonymousAccountStorage.swift
Sources/AIProxy/BackgroundNetworker.swift
Sources/AIProxy/DirectService.swift
Sources/AIProxy/ProtectedPropertyQueue.swift
Sources/AIProxy/ProxiedService.swift
Sources/AIProxy/Serializable.swift
Sources/AIProxy/ServiceMixin.swift

Configures the AIProxy SDK. Call this during app launch by adding an `init` to your SwiftUI MyApp.swift file, e.g.
import AIProxy
@main
struct ClientTesteriOSApp: App {
init() {
AIProxy.configure(
logLevel: .debug,
printRequestBodies: true,
printResponseBodies: true,
resolveDNSOverTLS: true,
useStableID: true
)
}
// ...
}
Or in your UIKit app's applicationDidFinishLaunching:
import AIProxy
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
var window: UIWindow?
func application(_ application: UIApplication,
didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
AIProxy.configure(
logLevel: .debug,
printRequestBodies: true,
printResponseBodies: true,
resolveDNSOverTLS: true,
useStableID: true
)
// ...
return true
}
// ...
}

Add a configuration method to be called at launch

---

Sources/AIProxy/OpenAI/OpenAIRealtimeConversationItemCreate.swift
Sources/AIProxy/OpenAI/OpenAIRealtimeMessage.swift
Sources/AIProxy/OpenAI/OpenAIRealtimeResponseCreate.swift
Sources/AIProxy/OpenAI/OpenAIRealtimeResponseFunctionCallArgumentsDone.swift
Sources/AIProxy/OpenAI/OpenAIRealtimeSession.swift
Sources/AIProxy/OpenAI/OpenAIRealtimeSessionConfiguration.swift

This change adds support for OpenAI Realtime tool calls.
I've never authored any Swift code before, so would love some feedback @lzell !
**Note**
I noticed in the OpenAI [docs](https://platform.openai.com/docs/api-reference/realtime-server-events/response/function_call_arguments/done), the `name` (i.e. the tool name) property of the `response.function_call_arguments.done` event is not present, however in the OpenAI playground the `name` is part of the payload, see screenshot below.

Add support for OpenAI Realtime API tool calls

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyDeviceCheck.swift
Sources/AIProxy/AIProxyIdentifier.swift
Sources/AIProxy/AIProxyURLRequest.swift
Sources/AIProxy/AIProxyURLSession.swift
Sources/AIProxy/AIProxyUtils.swift

Noticed this while evaluating the code—using "no-case" enums as "namespaces" directly makes the "namespace" type non-constructible.
Nice project, btw!

Change “namespace” type from struct -> enum.

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/Groq/GroqDirectService.swift
Sources/AIProxy/Groq/GroqProxiedService.swift
Sources/AIProxy/Groq/GroqService.swift

Groq requests were previously hardcoded to a max timeout of 60 seconds. It is now configurable by the caller

Expose secondsToWait for groq requests

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyURLRequest.swift
Sources/AIProxy/AIProxyUtils.swift
Sources/AIProxy/ClientLibErrorLogger.swift
Sources/AIProxy/RuntimeInfo.swift

Additional metadata to assist in understanding DC failures. They seem to be more frequent on macOS apps. Starting to collect stats on it.

Add additional request metadata

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyDeviceCheck.swift

This is a follow-up to https://github.com/lzell/AIProxySwift/pull/163
Nothing that I can find in the DCDevice.h or DeviceCheck docs indicate that this is necessary. However, I'm throwing this at the problem and then I will later revert if the remote logger branches introduced in PR 163 fire.

Isolate DeviceCheck to the main actor

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AudioController.swift
Sources/AIProxy/AudioPCMPlayer.swift
Sources/AIProxy/Gemini/GeminiGenerateContentRequestBody.swift

- Gemini's TTS model returns PCM16 data at 24khz. Conveniently, this is exactly the format of the player we already have for OpenAI realtime (seems likely google is gearing up to compete with realtime)
- There are two sample code snippets added to the README, one single speaker TTS and one multi-speaker TTS
- Also contains an audio capacity bug fix. I was previously setting the frame capacity of the transformed PCM buffer for playback (which needs to be PCM float 32) to the `sample rate * 2` rather than the `frame length * 2` of the incoming PCM16 buffer.

Add support for Gemini multi-speaker TTS

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/Replicate/ReplicateFluxKontextInputSchema.swift
Sources/AIProxy/Replicate/ReplicateService+Convenience.swift

- SOTA image editing models. They cost $0.04 per image for pro and $0.08 per image for max.
- Send up an image (encoded as data URL) and prompt to modify the image with.
- Both models get a convenience high level call in `ReplicateService+Convenience.swift`
- See the README additions for an example of using both models

Add support for Flux Kontext on Replicate

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyUtils.swift

- Customers have been writing in on Intercom that they can't build the main branch
- appTransactionID is available in Xcode 16.4
- Use compiler version as proxy for base SDK to conditionally branch around appTransactionID usage
https://developer.apple.com/documentation/storekit/transaction/apptransactionid
https://forums.swift.org/t/conditionally-compile-based-on-ios-version-previewcgimagerepresentation-broke/50883/2

Conditionally compile around appTransactionID availability

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/OpenAI/OpenAIDirectService.swift
Sources/AIProxy/OpenAI/OpenAIProxiedService.swift
Sources/AIProxy/OpenAI/OpenAIRequestFormat.swift

Added a new noVersionPrefix case to OpenAIRequestFormat enum to support custom versioning by including the version in the baseURL. This is particularly useful for API providers that use different version prefixes, like ByteDance's Volcengine which uses v3 instead of v1.
For example:
```swift
// For Volcengine API which uses v3:
let service = AIProxy.openAIDirectService(
unprotectedAPIKey: "your-api-key",
baseURL: "https://ark.cn-beijing.volces.com/api/v3",
requestFormat: .noVersionPrefix
)
```
This change provides more flexibility for API version handling by allowing users to include the version in the baseURL itself, rather than having it automatically added by the library.

feat: support custom versioning with noVersionPrefix format

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyIdentifier.swift
Sources/AIProxy/AIProxyURLRequest.swift
Sources/AIProxy/AIProxyUtils.swift
Sources/AIProxy/AnonymousAccount/AnonymousAccountStorage.swift
Sources/AIProxy/ClientLibErrorLogger.swift

With 'useStableID' enabled, we try to get a clientID through a series of fallbacks: appTransactionID, keychain-synced UUID, and finally IDFV. There are user reports of all three of these failing. This patch adds a final backstop, setting the clientID to "unknown"

Protect against a clientID of nil

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/DeepSeek/DeepSeekDirectService.swift
Sources/AIProxy/DeepSeek/DeepSeekProxiedService.swift
Sources/AIProxy/DeepSeek/DeepSeekService.swift
Sources/AIProxy/FireworksAI/FireworksAIDirectService.swift
Sources/AIProxy/FireworksAI/FireworksAIProxiedService.swift
Sources/AIProxy/FireworksAI/FireworksAIService.swift
Sources/AIProxy/Gemini/GeminiDirectService.swift
Sources/AIProxy/Gemini/GeminiProxiedService.swift
Sources/AIProxy/Gemini/GeminiService.swift
Sources/AIProxy/Groq/GroqDirectService.swift
Sources/AIProxy/Groq/GroqProxiedService.swift
Sources/AIProxy/Groq/GroqService.swift
Sources/AIProxy/Mistral/MistralDirectService.swift
Sources/AIProxy/Mistral/MistralProxiedService.swift
Sources/AIProxy/Mistral/MistralService.swift
Sources/AIProxy/OpenAI/OpenAIDirectService.swift
Sources/AIProxy/OpenAI/OpenAIProxiedService.swift
Sources/AIProxy/OpenAI/OpenAIService.swift
Sources/AIProxy/OpenRouter/OpenRouterDirectService.swift
Sources/AIProxy/OpenRouter/OpenRouterProxiedService.swift
Sources/AIProxy/OpenRouter/OpenRouterService.swift
Sources/AIProxy/Perplexity/PerplexityDirectService.swift
Sources/AIProxy/Perplexity/PerplexityProxiedService.swift
Sources/AIProxy/Perplexity/PerplexityService.swift
Sources/AIProxy/ServiceMixin.swift
Sources/AIProxy/TogetherAI/TogetherAIDirectService.swift
Sources/AIProxy/TogetherAI/TogetherAIProxiedService.swift
Sources/AIProxy/TogetherAI/TogetherAIService.swift

- Using much cleaner `AsyncThrowingStream` return types in all streaming functions.
- I was previously leaking details of how the async sequence was created, e.g. `AsyncCompactMapSequence<AsyncLineSequence<URLSession.AsyncBytes>...` was in the return type
- Callers shouldn't by concerned with the details of how the sequence is constructed. Instead they just want to loop over the streaming chunks, e.g. `AsyncThrowingStream<OpenAIChatCompletionChunk, Error>`
- Calling code remains unchanged, provided the user isn't manually annotating the return types.

Improve streaming fn signatures

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyError.swift
Sources/AIProxy/AIProxyURLRequest.swift

Apple's DeviceCheck is a core component of our security model.
We now enforce that all requests from the lib include either an `aiproxy-devicecheck` or `aiproxy-devicecheck-bypass` header. If neither of these are available, then we `raise` before the request is attempted.
If your app can't generate a DeviceCheck token from the device, then it is unable to make a request to AIProxy's backend.
In such a case, you can pop UI to the end user by catching AIProxyError.deviceCheckIsUnavailble:
```swift
let requestBody = OpenAIChatCompletionRequestBody(
model: "gpt-4.1-mini-2025-04-14",
messages: [
.system(content: .text("You are a helpful assistant")),
.user(content: .text("hello world"))
]
)
do {
let response = try await openAIService.chatCompletionRequest(
body: requestBody,
secondsToWait: 60 …
```

Enforce DeviceCheck token is populated in request headers

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/OpenAI/OpenAICreateResponseRequestBody.swift
Sources/AIProxy/OpenAI/OpenAIResponse.swift
Sources/AIProxy/OpenAI/OpenAIResponseStreamingEvent.swift
Sources/AIProxy/OpenAI/OpenAIResponseText.swift
Sources/AIProxy/OpenAI/OpenAIResponseTextConfiguration.swift
Tests/AIProxyTests/OpenAICreateResponseRequestTests.swift
Tests/AIProxyTests/OpenAIResponseObjectTests.swift

```swift
import AIProxy
/* Uncomment for BYOK use cases */
// let openAIService = AIProxy.openAIDirectService(
//     unprotectedAPIKey: "your-openai-key"
// )
/* Uncomment for all other production use cases */
// let openAIService = AIProxy.openAIService(
//     partialKey: "partial-key-from-your-developer-dashboard",
//     serviceURL: "service-url-from-your-developer-dashboard"
// )
let schema: [String: AIProxyJSONValue] = [
"type": "object",
"properties": [
"colors": [
"type": "array",
"items": [
"type": "object",
"properties": [
"name": [
"type": "string",
"description": "A descriptive name to give the color"
],
"hex_code": [
"type": "string",
"description": "The hex code of the color"
]
],
"required": ["name", "hex_code"],
"additionalProperties": false
]
]
],
"required": ["colors"], …
```

Add support for Structured Outputs through OpenAI Responses API

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/AIProxyConfiguration.swift
Sources/AIProxy/AIProxyIdentifier.swift
Sources/AIProxy/AIProxyUtils.swift
Sources/AIProxy/AnonymousAccount/AnonymousAccountStorage.swift
Sources/AIProxy/ProtectedPropertyQueue.swift
Sources/AIProxy/Serializable.swift
Sources/AIProxy/ServiceMixin.swift

- There's a report in the wild of multiple `AIProxy.configure` calls causing a bad access when setting up the stable anon identifier.
- The `configure` method now sets up the stable ID only once, regardless of number of times `configure` is called.
- Cleaned up `AIProxy.swift`, the main interface into the lib, by moving some configuration options and protected accessors to `AIProxyConfiguration.swift`

Protect against multiple configure calls

---

README.md
Sources/AIProxy/AIProxy.swift
Sources/AIProxy/OpenAI/OpenAICreateImageEditRequestBody.swift
Tests/AIProxyTests/OpenAIEditImageRequestTests.swift

Issue: https://github.com/lzell/AIProxySwift/issues/200
```swift
import AIProxy
/* Uncomment for BYOK use cases */
// let openAIService = AIProxy.openAIDirectService(
//     unprotectedAPIKey: "your-openai-key"
// )
/* Uncomment for all other production use cases */
// let openAIService = AIProxy.openAIService(
//     partialKey: "partial-key-from-your-developer-dashboard",
//     serviceURL: "service-url-from-your-developer-dashboard"
// )
let openAIService = getOpenAIService(config)
guard let image = UIImage(named: "my-image") else {
print("Could not find an image named 'my-image' in your app assets")
return
}
guard let jpegData = AIProxy.encodeImageAsJpeg(image: image, compressionQuality: 0.5) else {
print("Could not encode image as jpeg")
return
}
let requestBody = …
```

Add support for OpenAI high fidelity image edit

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/OpenAI/OpenAICreateResponseRequestBody.swift

Example of passing a safety identifier:
```swift
let requestBody = OpenAICreateResponseRequestBody(
input: .text("hello world"),
model: "gpt-4.1-mini",
safetyIdentifier: "123",
)
let response = try await openAIService.createResponse(
requestBody: requestBody,
secondsToWait: 120
)
print(response.outputText)
```

Add safety identifier to responses API

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/OpenAI/OpenAICreateImageEditRequestBody.swift
Tests/AIProxyTests/OpenAIEditImageRequestTests.swift

Image edits can produce transparent background using `gpt-image-1`. For example:
```swift
let requestBody = OpenAICreateImageEditRequestBody(
images: [.jpeg(myImageData)],
prompt: "Change the coffee cup to red",
background: .transparent,
inputFidelity: .high,
model: .gptImage1,
outputFormat: .png
)
```

Add background option to OpenAI's edit image

---

Sources/AIProxy/AIProxy.swift
Sources/AIProxy/OpenAI/OpenAICreateResponseRequestBody.swift

- Our own usage of `webSearchPreview` was causing compiler warnings, which we want to prevent on main
- For now I've disabled the deprecation notices. I will likely go through the process of adapting callers of `webSearchPreview` to use `webSearch` under the hood and add the deprecation notices back in. But for now, I will leave them as available in case an existing caller needs parity with pre AIProxySwift 0.129.0 OpenAI web search behavior

Bump sdkVersion and remove deprecation warnings on search preview

---

Sources/AIProxy/AIProxyRequestBuilder.swift
Sources/AIProxy/EachAI/EachAIService.swift
Sources/AIProxy/OpenAI/OpenAIDirectRequestBuilder.swift
Sources/AIProxy/OpenAI/OpenAIProxiedRequestBuilder.swift
Sources/AIProxy/OpenAI/OpenAIService.swift

This type is generic enough to be used in multiple places (and already is used between OpenAI and EachAI)

Rename OpenAIRequestBuilder -> AIProxyRequestBuilder
