lzell/AIProxySwift

- Examples/README.md
- README.md
- Link to sample apps from main README
- Add build instructions for the `AIColorPalette` sample project
> Add README and build instructions for sample app

- README.md
- Added installation section
- Added updating section
- Added troubleshooting item for running XCTest UI test cases
- Added troubleshooting item for missing the module import
> Add images to the README for installing, updating, and troubleshooting

- Sources/AIProxy/AIProxyUtils.swift
- Sources/AIProxy/Replicate/ReplicatePredictionResponseBody.swift
- Sources/AIProxy/Replicate/ReplicateTrainingResponseBody.swift
- Tests/AIProxyTests/ReplicateTrainingResponseBodyTests.swift
> Remove data stripping utility

- README.md
- Sources/AIProxy/AIProxyError.swift
- Sources/AIProxy/Replicate/ReplicateError.swift
- Sources/AIProxy/Replicate/ReplicateService.swift
- Improved replicate error messages
- Improved AIProxyError error messages
- Improved error messages in the README snippets
> Improved error messages

- Sources/AIProxy/Anthropic/AnthropicService.swift
- Sources/AIProxy/DeepL/DeepLService.swift
- Sources/AIProxy/ElevenLabs/ElevenLabsService.swift
- Sources/AIProxy/Fal/FalService.swift
- Sources/AIProxy/Gemini/GeminiService.swift
- Sources/AIProxy/Groq/GroqService.swift
- Sources/AIProxy/OpenAI/OpenAIService.swift
- Sources/AIProxy/Replicate/ReplicateService.swift
- Sources/AIProxy/StabilityAI/StabilityAIService.swift
- Sources/AIProxy/TogetherAI/TogetherAIService.swift
All public classes are now `open`.
Motivating comment: https://github.com/lzell/AIProxySwift/pull/60#issuecomment-2437303543
> Use open classes so customers can override behavior

- Sources/AIProxy/Anthropic/AnthropicService.swift
- Sources/AIProxy/DeepL/DeepLService.swift
- Sources/AIProxy/ElevenLabs/ElevenLabsService.swift
- Sources/AIProxy/Fal/FalService.swift
- Sources/AIProxy/Gemini/GeminiService.swift
- Sources/AIProxy/Groq/GroqService.swift
- Sources/AIProxy/OpenAI/OpenAIService.swift
- Sources/AIProxy/Replicate/ReplicateService.swift
- Sources/AIProxy/StabilityAI/StabilityAIService.swift
- Sources/AIProxy/TogetherAI/TogetherAIService.swift
@lzell Package was not compiling for me due to `public open class`
Tried to do the fix here. But feel free to change however you need.
> Fixed open declaration #60

- Sources/AIProxy/ElevenLabs/ElevenLabsTTSRequestBody.swift
Adding public memberwise initializer for ElevenLabsTTSRequestBody
> Add public memberwise init for ElevenLabsTTSRequestBody

- README.md
- Sources/AIProxy/Replicate/ReplicateFaceSwapInputSchema.swift
- Sources/AIProxy/Replicate/ReplicateFaceSwapOutputSchema.swift
- Sources/AIProxy/Replicate/ReplicateService+Convenience.swift
- Tests/AIProxyTests/ReplicateFaceSwapOutputSchemaTests.swift
- Tests/AIProxyTests/TogetherAIChatCompletionStreamingChunkTests.swift
Convenience method for calling https://replicate.com/xiankgx/face-swap
> Add replicate faceswap convenience method

- Sources/AIProxy/AIProxy.swift
- Sources/AIProxy/AIProxyUtils.swift
If mac catalyst is the target, rely on UIKit instead of AppKit
> Add conditional fixes for mac catalyst

- README.md
Documented a useful approach for continuing a conversation with the model.
> Add OpenAI example of feeding chat history back to model

- Sources/AIProxy/AIProxy.swift
- Sources/AIProxy/ReceiptValidation/ReceiptValidationRequestBody.swift
- Sources/AIProxy/RemoteLogger/RemoteLoggerService.swift
- Sources/AIProxy/Replicate/ReplicateDirectService.swift
- Sources/AIProxy/Replicate/ReplicateProxiedService.swift
- Sources/AIProxy/Replicate/ReplicateService+Convenience.swift
- Sources/AIProxy/Replicate/ReplicateService.swift
- Adds a breadcrumb logger with optional error message
- Updates to latest Replicate type away from deprecated type
> Add remote logger service

- README.md
- Sources/AIProxy/AIProxy.swift
- Sources/AIProxy/AIProxyURLRequest.swift
- Sources/AIProxy/AnonymousAccount/AIProxyStorage.swift
- Sources/AIProxy/AnonymousAccount/AnonymousAccountStorage.swift
- Sources/AIProxy/Brave/BraveDirectService.swift
- Sources/AIProxy/Brave/BraveProxiedService.swift
- Sources/AIProxy/Brave/BraveService.swift
- Sources/AIProxy/Brave/BraveWebSearchResponseBody.swift
- Sources/AIProxy/OpenRouter/OpenRouterDirectService.swift
- Sources/AIProxy/RemoteLogger/RemoteLoggerService.swift
- Tests/AIProxyTests/BraveWebSearchResponseTests.swift
- Tests/AIProxyTests/OpenAIChatCompletionRequestTests.swift
- Added support for https://api-dashboard.search.brave.com/app/documentation/web-search/get-started
- Added README example for making a web search request to understand swift concurrency
> Add Brave web search support

- README.md
- Sources/AIProxy/AIProxy.swift
- Sources/AIProxy/AIProxyCertificatePinning.swift
- Sources/AIProxy/AIProxyDeviceCheck.swift
- Sources/AIProxy/AIProxyLogger.swift
- Sources/AIProxy/AnonymousAccount/AIProxyKeychain.swift
- Sources/AIProxy/AnonymousAccount/AnonymousAccountStorage.swift
- Sources/AIProxy/Anthropic/AnthropicMessageStreamingContentBlockStart.swift
- Sources/AIProxy/Anthropic/AnthropicMessageStreamingDeltaBlock.swift
- Sources/AIProxy/AudioPCMPlayer.swift
- Sources/AIProxy/AudioPCMPlayerError.swift
- Sources/AIProxy/Deserializable.swift
- Sources/AIProxy/FireworksAI/FireworksAIDirectService.swift
- Sources/AIProxy/FireworksAI/FireworksAIProxiedService.swift
- Sources/AIProxy/MicrophonePCMSampleVendor.swift
- Sources/AIProxy/MicrophonePCMSampleVendorError.swift
- Sources/AIProxy/MicrophoneSampleVendor.swift
- Sources/AIProxy/OpenAI/OpenAIDirectService.swift
- Sources/AIProxy/OpenAI/OpenAIProxiedService.swift
- Sources/AIProxy/OpenAI/OpenAIRealtimeConversationItemCreate.swift
- Sources/AIProxy/OpenAI/OpenAIRealtimeInputAudioBufferAppend.swift
- Sources/AIProxy/OpenAI/OpenAIRealtimeInputAudioBufferSpeechStarted.swift
- Sources/AIProxy/OpenAI/OpenAIRealtimeMessage.swift
- Sources/AIProxy/OpenAI/OpenAIRealtimeResponseCreate.swift
- Sources/AIProxy/OpenAI/OpenAIRealtimeSession.swift
- Sources/AIProxy/OpenAI/OpenAIRealtimeSessionConfiguration.swift
- Sources/AIProxy/OpenAI/OpenAIRealtimeSessionUpdate.swift
- Sources/AIProxy/OpenAI/OpenAIService.swift
- Sources/AIProxy/RealtimeActor.swift
- Sources/AIProxy/Replicate/ReplicateService.swift
- Added an audio conversation example that works on both iOS and macOS
- Please see the README for a copy-pasteable snippet to try realtime
> Add OpenAI realtime support

- README.md
- Sources/AIProxy/Gemini/GeminiGenerateContentRequestBody.swift
- Tests/AIProxyTests/GeminiStructuredOutputsRequestTests.swift
- Fixed bug of snake casing arguments sent up to Gemini. Gemini expects camelCase
- Added readme example for using Gemini structured outputs
> Add support for Gemini structured outputs

- README.md
- Sources/AIProxy/Gemini/GeminiGenerateContentResponseBody.swift
- Tests/AIProxyTests/GeminiGenerateImageResponseTests.swift
- Added example to the readme of generating an image with `gemini-2.0-flash-exp-image-generation`
> Add Gemini image generation support

- Sources/AIProxy/Anthropic/AnthropicMessageResponseBody.swift
This change allows external modules to access usage statistics.
> Public inputTokens and outputTokens in AnthropicMessageUsage

- README.md
- Sources/AIProxy/AIProxy.swift
- Sources/AIProxy/OpenAI/OpenAICreateResponseRequestBody.swift
- Tests/AIProxyTests/OpenAICreateResponseRequestTests.swift
> Add OpenAI Responses example using two images as inputs

- Sources/AIProxy/OpenAI/OpenAICreateResponseRequestBody.swift
Tool usage examples: 
```swift
// Web Search
static public func makeRequestWithWebSearch(
withText text: String,
previousResponseId: String?,
searchContextSize: OpenAICreateResponseRequestBody.WebSearchTool.SearchContextSize?,
userLocation: OpenAICreateResponseRequestBody.WebSearchTool.UserLocation?
) async throws -> OpenAIResponse {
let webSearchTool: OpenAICreateResponseRequestBody.WebSearchTool = .init(
searchContextSize: searchContextSize,
userLocation: userLocation
)
let requestBody = OpenAICreateResponseRequestBody(
input: .text(text),
model: model,
tools: [.webSearch(webSearchTool)],
previousResponseId: previousResponseId
)
do {
let response: OpenAIResponse = try await openAIService.createResponse(requestBody: requestBody)
return response
} catch …
```
> fixed the type field for tools in responses API

- Sources/AIProxy/OpenAI/OpenAIRealtimeMessage.swift
- Sources/AIProxy/OpenAI/OpenAIRealtimeSession.swift
Added the missing cases that enable correct handling of transcription events for realtime sessions.
> Add support for transcription message types

- README.md
- Sources/AIProxy/AIProxy.swift
- Sources/AIProxy/Gemini/GeminiDirectService.swift
- Sources/AIProxy/Gemini/GeminiProxiedService.swift
- Sources/AIProxy/Gemini/GeminiService.swift
- Streaming gemini responses works with text, image, and video inputs
- Added streaming example to README
> Add Gemini streaming support
